### PR TITLE
configurations.nix: set pkgs instead of system

### PR DESCRIPTION
**Pull request by Mic92**
This should save evaluation time and memory

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I locally still need to set system and setting pkgs broke nixpkgs.overlays

**Comment by Mic92** [comment]
We don't use overlays here. However overlays also seems to be an issue: https://buildbot.dse.in.tum.de/#/builders/8/builds/340

**Comment by SuperSandro2000** [comment]
> We don't use overlays here.

that will bite you back in the future, I'll promise.

**Comment by Mic92** [comment]
I was primarily interested in how much performance this gains in real-world systems. If it doesn't safe significantly cpu time/memory, I will revert. I actually find overlays one of the most confusing systems we have, so I wouldn't miss them a lot.

**Comment by Mic92** [comment]
After:

nix eval --impure --expr 'import ./all-configs.nix' --builders ''  40.69s user 7.10s system 79% cpu 1:00.10 total


Before:

noglob nix eval --impure --expr 'import ./all-configs.nix' --builders ''  58.56s user 12.21s system 78% cpu 1:30.15 total

so like 30 percent across the board?

**Comment by Mic92** [comment]
And half the memory usage:

Before 7751790592 
After: 4262653952 
-> 45% less

**Comment by Mic92** [comment]
> > We don't use overlays here.
> 
> that will bite you back in the future, I'll promise. Silenting discarding all overlays is just up for being forgotten and using hours to figure out why.

nixpkgs.config is actually the trickier one i.e. if you need unfree. It's still possible to have overlays with this approach because one could just create one global nixpkgs instances that have them in flake-parts but this one wouldn't be than used in the other flake inputs. It would be actually cooler if it was easiert merge overlays and nixpkgs config instead of having to re-import nixpkgs every time.

**Pull request merged**
