### PR TITLE
delete sys-lab-#2 students and ssh keys & FPGA configuration for new servers

### PR DESCRIPTION
**Pull request by AtsushiKoshiba**

### CODE REVIEW

**Comment by AtsushiKoshiba** [comment]
Oh I shouldn't remove Yi He as he's a HiWi student. I'll fix this

**Comment by AtsushiKoshiba** [comment]
@pogobanane Hi, do you have any idea to solve this error? Apparently, my sops secret is not properly loaded, but my secret is already registered. 

```
these 2 derivations will be built:
  /nix/store/063jb7zim0x497kp221nyk5aljh8hkb6-manifest-for-users.json.drv
  /nix/store/hczw1hlifgsxxqzw0nkvq9mm5pw08h50-nixos-system-clara-22.11.20230128.0945db2.drv
building '/nix/store/063jb7zim0x497kp221nyk5aljh8hkb6-manifest-for-users.json.drv'...
manifest-for-users.json> /nix/store/0ywdn6vbs49w9mpcb62aa2r7nc3l85bj-sops-install-secrets-0.0.1/bin/sops-install-secrets: Manifest is not valid: secret atsushi-password-hash in /nix/store/gdb6ag7z70y32f9cj30dzpgz83qxgc09-clara.yml is not valid: The key 'atsushi-password-hash' cannot be found
error: builder for '/nix/store/063jb7zim0x497kp221nyk5aljh8hkb6-manifest-for-users.json.drv' failed with exit code 1;
       last 1 log lines:
       > /nix/store/0ywdn6vbs49w9mpcb62aa2r7nc3l85bj-sops-install-secrets-0.0.1/bin/sops-install-secrets: Manifest is not valid: secret atsushi-password-hash in /nix/store/gdb6ag7z70y32f9cj30dzpgz83qxgc09-clara.yml is not valid: The key 'atsushi-password-hash' cannot be found
       For full logs, run 'nix log /nix/store/063jb7zim0x497kp221nyk5aljh8hkb6-manifest-for-users.json.drv'.
error: 1 dependencies of derivation '/nix/store/hczw1hlifgsxxqzw0nkvq9mm5pw08h50-nixos-system-clara-22.11.20230128.0945db2.drv' failed to build
```

**Comment by pogobanane** [comment]
you also need to set xrdp passwords for xrdp users with `sops hosts/clara.yml` etc [1]. Looking at the other hosts/*.ymls, i guess you used the xilinx xrdp user and password so far. You could just copy paste that. Or generate a new one with `inv generate-password --user atsushi` and paste that into `sops hosts/clara.yml`. 

[1] https://github.com/TUM-DSE/doctor-cluster-config/blob/dbb03869abc6728970f5f82456040f58406aa863/modules/xrdp-passwords.nix#L26

**Comment by AtsushiKoshiba** [comment]
Got it, thanks. I was only seeing `hosts/*.nix` files.

**Comment by AtsushiKoshiba** [comment]
@pogobanane I've updated `hosts/*.yml`. It seems working well. Apparently, I also have to add passwords for xrdp users written in [modules/xrdp-passwords.nix](https://github.com/TUM-DSE/doctor-cluster-config/blob/dbb03869abc6728970f5f82456040f58406aa863/modules/xrdp-passwords.nix#L31). Then all checks have passed.

**Pull request merged**
