### PR TITLE
fix: bump sev kernel + enable hugepages

### PR DESCRIPTION
**Pull request by enterJazz**
- kernel to 6.5.0-rc2: required to start sev-snp guest; else doesn't start (bug)
- hugepages: required for spdk vhost-blk
- dpdk: disable for kernel 6.5 -> kmod build breaks (see #383)

CC @pogobanane #383

### CODE REVIEW

**Comment by enterJazz** [comment]
BTW @Mic92 `nix flake check` appears to not be working on the current head.

```
$ nix flake check
error: cannot build '/nix/store/pxn8n3ls4dximssfk5fsyl1xm81gabmd-config.nix.drv' during evaluation because the option 'allow-import-from-derivation' is disabled
(use '--show-trace' to show detailed location information)
$ nix flake check --allow-import-from-derivation
error: a 'aarch64-linux' with features {} is required to build '/nix/store/dbkfrandir5c6yzgbkzkxiwpwfa9aywh-config.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
(use '--show-trace' to show detailed location information)
$ inv flake-check
$ nix flake check --option allow-import-from-derivation true
error: a 'aarch64-linux' with features {} is required to build '/nix/store/dbkfrandir5c6yzgbkzkxiwpwfa9aywh-config.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
(use '--show-trace' to show detailed location information)
```
performed on current master 4bb1522c4050f9f9923e15ba5b757d82dd379349

should I go ahead and create an issue?

**Comment by Mic92** [comment]
Looks like this is the kernel config for our Mac mini. Just do --allow-import-from-derivation

**Comment by enterJazz** [comment]
> Looks like this is the kernel config for our Mac mini. Just do --allow-import-from-derivation

from my original comment:
> $ nix flake check --allow-import-from-derivation
error: a 'aarch64-linux' with features {} is required to build '/nix/store/dbkfrandir5c6yzgbkzkxiwpwfa9aywh-config.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
(use '--show-trace' to show detailed location information)

doesn't appear to work

**Comment by Mic92** [comment]
This is because we also have the aarch64 machine in the check output for x86. Could better sorted. You can add a remote builder via aarch64 for now

**Comment by enterJazz** [comment]
> This is because we also have the aarch64 machine in the check output for x86. Could better sorted. You can add a remote builder via aarch64 for now

I'm afraid I don't understand.
1. what is the check output for x86?
2. what is the remote builder, and where do I add it?

thanks

**Comment by Mic92** [comment]
Rather than hydraJobs in the flake we can change this to checks.x86_64-linux and checks.aarch64-linux. Than nix flake check will ignore nixos configurations that it cannot build for:

```
$ nix flake show --allow-import-from-derivation 
├───apps
│   ├───aarch64-darwin
│   ├───aarch64-linux
│   └───x86_64-linux
├───checks
│   ├───aarch64-darwin
│   ├───aarch64-linux
│   └───x86_64-linux
├───devShells
│   ├───aarch64-darwin
│   │   ├───ansible: development environment 'nix-shell'
│   │   └───default: development environment 'nix-shell'
│   ├───aarch64-linux
│   │   ├───ansible: development environment 'nix-shell'
│   │   └───default: development environment 'nix-shell'
│   └───x86_64-linux
│       ├───ansible: development environment 'nix-shell'
│       └───default: development environment 'nix-shell'
├───formatter
├───hydraJobs
│   ├───devShells: derivation 'nix-shell'
│   ├───nixos-adelaide: derivation 'nixos-system-adelaide-23.05.20231004.ec2e6ab'
│   ├───nixos-amy: derivation 'nixos-system-amy-23.05.20231004.ec2e6ab'
│   ├───nixos-astrid: derivation 'nixos-system-astrid-23.05.20231004.ec2e6ab'
│   ├───nixos-bill: derivation 'nixos-system-bill-23.05.20231004.ec2e6ab'
│   ├───nixos-christina: derivation 'nixos-system-christina-23.05.20231004.ec2e6ab'
│   ├───nixos-clara: derivation 'nixos-system-clara-23.05.20231004.ec2e6ab'
│   ├───nixos-dan: derivation 'nixos-system-dan-23.05.20231004.ec2e6ab'
│   ├───nixos-doctor: derivation 'nixos-system-doctor-23.05.20231004.ec2e6ab'
trace: warning: Please add network configuration for donna. None found in /nix/store/xi8pi9h33f546609vgqdik9fpimk1b2c-hosts.nix
trace: warning: Please set simd.arch for donna
│   ├───nixos-donna: derivation 'nixos-system-donna-23.05.20231004.ec2e6ab'
│   ├───nixos-graham: derivation 'nixos-system-graham-23.05.20231004.ec2e6ab'
│   ├───nixos-jack: derivation 'nixos-system-jack-23.05.20231004.ec2e6ab'
│   ├───nixos-jackson: derivation 'nixos-system-jackson-23.05.20231004.ec2e6ab'
│   ├───nixos-mickey: derivation 'nixos-system-mickey-23.05.20231004.ec2e6ab'
│   ├───nixos-nardole: derivation 'nixos-system-nardole-23.05.20231004.ec2e6ab'
│   ├───nixos-river: derivation 'nixos-system-river-23.05.20231004.ec2e6ab'
│   ├───nixos-rose: derivation 'nixos-system-rose-23.05.20231004.ec2e6ab'
trace: warning: Please set simd.arch for ruby
│   ├───nixos-ruby: derivation 'nixos-system-ruby-23.05.20231004.ec2e6ab'
│   ├───nixos-ryan: derivation 'nixos-system-ryan-23.05.20231004.ec2e6ab'
trace: warning: Please set simd.arch for vislor
│   ├───nixos-vislor: derivation 'nixos-system-vislor-23.05.20231004.ec2e6ab'
│   ├───nixos-wilfred: derivation 'nixos-system-wilfred-23.05.20231004.ec2e6ab'
trace: warning: Please set simd.arch for yasmin
│   └───nixos-yasmin: derivation 'nixos-system-yasmin-23.05.20231004.ec2e6ab'
├───legacyPackages
│   ├───aarch64-darwin omitted (use '--legacy' to show)
│   ├───aarch64-linux omitted (use '--legacy' to show)
│   └───x86_64-linux omitted (use '--legacy' to show)
```

For remote builder you can ask Peter. Otherwise checkout https://nixos.org/manual/nix/stable/advanced-topics/distributed-builds.html

This is what I have in my nixos module in my dotfiles: https://github.com/Mic92/dotfiles/blob/main/nixos/turingmachine/modules/remote-builder.nix

**Comment by enterJazz** [comment]
I would go ahead and merge this for now. I'll check out the remote builder when @pogobanane is in the office again to help me out

**Pull request merged**
