### PR TITLE
add ssh key for mgugat

### PR DESCRIPTION
**Pull request by DeeJayBro**
I attend this semesters Sys-Seminar.

For my experiment, I would like to benchmark several filesystems tailored for flash storage like F2FS, FlashLight or ParaFS with the Phoronix Test Suite.

### CODE REVIEW

**Comment by Mic92** [comment]
Hi. For the other mentioned filesystems do you need any special kernel modules? If that's the case we might need to give a you machine instead, where you get the full control. Apart from that for phoronix I would recommend you to use the provided docker images as it already bundles all implicit dependencies.

**Comment by DeeJayBro** [comment]
Thanks for the tip, so I would already need to build my own kernel for BetrFS so the full kernel control would be a good idea.

**Comment by Mic92** [comment]
Ok. In that case, you will have an easier time, if you sign up here: https://cloudlab.us/signup.php
and put in [Serverless-tum](https://www.cloudlab.us/show-project.php?project=Serverless-tum) as an existing project to join.
Once you are part of this you can boot up nodes with the OS of your choice and have full control over everything.

**Comment by Mic92** [comment]
cc @harshanavkis to accept the project join request of @DeeJayBro

**Comment by Mic92** [comment]
@DeeJayBro any updates on this?

**Comment by DeeJayBro** [comment]
I was successfully able to use cloudlab for my benchmarks, so this pull can be closed

**Pull request closed without merging**
