### PR TITLE
user: remove moritz

### PR DESCRIPTION
**Pull request by mmisono**

### CODE REVIEW

**Comment by mmisono** [comment]
What's this CI error?

```
these 3 derivations will be built:
 /nix/store/bn7v9i9ygww3nbm5dpx0x87shq3194s1-manifest.json.drv
 /nix/store/qmlzgjbzd237gw1zm0ai5a4fgmdihjz6-manifest-for-users.json.drv
 /nix/store/3jwx5q8sx20vg59m1zn9kgkswjh56k8s-nixos-system-bill-23.11.20240406.c36b6f6.drv
building '/nix/store/qmlzgjbzd237gw1zm0ai5a4fgmdihjz6-manifest-for-users.json.drv'...
building '/nix/store/bn7v9i9ygww3nbm5dpx0x87shq3194s1-manifest.json.drv'...
manifest-for-users.json> /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 14: 8 Segmentation fault (core dumped) /nix/store/lngxz1q4dwf3xjsmvyaahjw3lwjid45i-sops-install-secrets-0.0.1/bin/sops-install-secrets -check-mode=sopsfile "$out"
error: builder for '/nix/store/qmlzgjbzd237gw1zm0ai5a4fgmdihjz6-manifest-for-users.json.drv' failed with exit code 139;
 last 1 log lines:
 > /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 14: 8 Segmentation fault (core dumped) /nix/store/lngxz1q4dwf3xjsmvyaahjw3lwjid45i-sops-install-secrets-0.0.1/bin/sops-install-secrets -check-mode=sopsfile "$out"
 For full logs, run 'nix log /nix/store/qmlzgjbzd237gw1zm0ai5a4fgmdihjz6-manifest-for-users.json.drv'.
manifest.json> /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 14: 8 Segmentation fault (core dumped) /nix/store/lngxz1q4dwf3xjsmvyaahjw3lwjid45i-sops-install-secrets-0.0.1/bin/sops-install-secrets -check-mode=sopsfile "$out"
error: builder for '/nix/store/bn7v9i9ygww3nbm5dpx0x87shq3194s1-manifest.json.drv' failed with exit code 139;
 last 1 log lines:
 > /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 14: 8 Segmentation fault (core dumped) /nix/store/lngxz1q4dwf3xjsmvyaahjw3lwjid45i-sops-install-secrets-0.0.1/bin/sops-install-secrets -check-mode=sopsfile "$out"
 For full logs, run 'nix log /nix/store/bn7v9i9ygww3nbm5dpx0x87shq3194s1-manifest.json.drv'.
error: 2 dependencies of derivation '/nix/store/3jwx5q8sx20vg59m1zn9kgkswjh56k8s-nixos-system-bill-23.11.20240406.c36b6f6.drv' failed to build
```

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify rebase

**Pull request merged**
